#-----------------------------------------------------------------------------------------------------------------------
spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  #---------------------------------------------------------------------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: false
#    open-in-view: false
    properties:
      hibernate:
        default_schema: elethu
  #---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: jdbc:h2:mem:ikamva-test;INIT=CREATE SCHEMA IF NOT EXISTS elethu
    username: ikamva
    password: ikamva
    driverClassName: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: czyawa@gmail.com
    password: TBC
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
        transport: smtp
    protocol: smtp

  h2:
    console:
      enabled: false
#-----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: logs/ikamva-elethu-application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - [%file : %line] - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %magenta([%thread]) %cyan(%logger{36}) - %clr([%file : %line]) - %msg%n"
  level:
    elethu.ikamva.services: ERROR
    elethu.ikamva.web: ERROR
    elethu.ikamva.repositories: ERROR
    elethu.ikamva.controllers: ERROR
    elethu.ikamva.config: ERROR
    elethu.ikamva.application: DEBUG
    elethu.ikamva.filter: ERROR
    elethu.ikamva.security: ERROR
    elethu.ikamva.utils: ERROR
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 10MB
#-----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#-----------------------------------------------------------------------------------------------------------------------
info:
  app:
    name: "Elethu Ikamva Portal"
#-----------------------------------------------------------------------------------------------------------------------




