#-----------------------------------------------------------------------------------------------------------------------
#Start :: Spring Boot configuration for development environment
#-----------------------------------------------------------------------------------------------------------------------
SERVER_PORT: 8083
#-----------------------------------------------------------------------------------------------------------------------
# Spring: Servlet
#-----------------------------------------------------------------------------------------------------------------------
ENABLE_ANSI: always
MULTIPART_ENABLED: true
MAX_FILE_SIZE: 2MB
MAX_REQUEST_SIZE: 2MB
#-----------------------------------------------------------------------------------------------------------------------
# Spring: JPA:
#-----------------------------------------------------------------------------------------------------------------------
HIBERNATE_DDL_AUTO: update
HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
GENERATE_DDL: true
SHOW_SQL: false
OPEN_IN_VIEW: false
DEFAULT_SCHEMA: elethu
H2_CONSOLE_ENABLED: false
SQL_INIT_PLATFORM: postgres
#-----------------------------------------------------------------------------------------------------------------------
# Datasource:
#-----------------------------------------------------------------------------------------------------------------------
DATASOURSE_URL: jdbc:postgresql://localhost:5432/ikamvadb
DATASOURSE_USERNAME: zukoyawa
DATASOURSE_PASSWORD: ^Wu3H1bE4Gr*nJxPpTME7!t
DATASOURSE_DRIVER_CLASS_NAME: org.postgresql.Driver
#-----------------------------------------------------------------------------------------------------------------------
# Mail:
#-----------------------------------------------------------------------------------------------------------------------
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: czyawa@gmail.com
MAIL_PASSWORD: TBC
#-----------------------------------------------------------------------------------------------------------------------
# Logging:
#-----------------------------------------------------------------------------------------------------------------------
LOGGING_FILE_NAME: logs/ikamva-elethu-application.log
LOGGING_ROLLING_POLICY_MAX_HISTORY: 14
LOGGING_ROLLING_POLICY_MAX_FILE_SIZE: 10MB
#----------------------------------------------------------------------------------------------------------------------
# Spring: Profiles:
#-----------------------------------------------------------------------------------------------------------------------
ACTIVE_PROFILE: prod
#-----------------------------------------------------------------------------------------------------------------------
# Spring: Security:
#-----------------------------------------------------------------------------------------------------------------------
JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
JWT_EXPIRATION_IN_MS: 3600000
JWT_REFRESH_EXPIRATION_IN_MS: 86400000
#-----------------------------------------------------------------------------------------------------------------------
#End :: Spring Boot configuration for development environment
#-----------------------------------------------------------------------------------------------------------------------