#-----------------------------------------------------------------------------------------------------------------------
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
#-----------------------------------------------------------------------------------------------------------------------
spring:
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console
  output:
    ansi:
      enabled: ${ENABLE_ANSI}
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED}
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  jpa:
    show-sql: ${SHOW_SQL}
    generate-ddl: ${GENERATE_DDL}
    open-in-view: ${OPEN_IN_VIEW}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    database-platform: ${HIBERNATE_DIALECT}
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA}
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: ${DATASOURSE_URL}
    username: ${DATASOURSE_USERNAME}
    password: ${DATASOURSE_PASSWORD}
    driverClassName: ${DATASOURSE_DRIVER_CLASS_NAME}
  sql:
    init:
      platform: ${SQL_INIT_PLATFORM}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
        transport: smtp
    protocol: smtp

logging:
  file:
    name: ${LOGGING_FILE_NAME}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - [%file : %line] - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %magenta([%thread]) %cyan(%logger{36}) - %clr([%file : %line]) - %msg%n"
  level:
    elethu.ikamva.web: ${LOGGING_LEVEL_WEB:INFO}
    elethu.ikamva.utils: ${LOGGING_LEVEL_UTILS:INFO}
    elethu.ikamva.config: ${LOGGING_LEVEL_CONFIG:DEBUG}
    elethu.ikamva.filter: ${LOGGING_LEVEL_FILTER:ERROR}
    elethu.ikamva.security: ${LOGGING_LEVEL_SECURITY:DEBUG}
    elethu.ikamva.services: ${LOGGING_LEVEL_SERVICES:INFO}
    elethu.ikamva.controllers: ${LOGGING_LEVEL_CONTROLLERS:INFO}
    elethu.ikamva.application: ${LOGGING_LEVEL_APPLICATION:INFO}
    elethu.ikamva.repositories: ${LOGGING_LEVEL_REPOSITORIES:ERROR}
  logback:
    rollingpolicy:
      max-history: ${LOGGING_ROLLING_POLICY_MAX_HISTORY}
      max-file-size: ${LOGGING_ROLLING_POLICY_MAX_FILE_SIZE}
application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION_IN_MS}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION_IN_MS}

# Thread pool configuration
threading:
  completable-future:
    max-pool-size: ${THREADING_COMPLETABLE_FUTURE_MAX_POOL_SIZE:10}
    core-pool-size: ${THREADING_COMPLETABLE_FUTURE_CORE_POOL_SIZE:10}
    queue-capacity: ${THREADING_COMPLETABLE_FUTURE_QUEUE_CAPACITY:100}
    thread-name-prefix: ${THREADING_COMPLETABLE_FUTURE_THREAD_NAME_PREFIX:Ikamva-Completable-Future-}
