#-----------------------------------------------------------------------------------------------------------------------
#Start :: Spring Boot configuration for development environment
#-----------------------------------------------------------------------------------------------------------------------
SERVER_PORT: 8081
#-----------------------------------------------------------------------------------------------------------------------
# Spring: Servlet
#-----------------------------------------------------------------------------------------------------------------------
ENABLE_ANSI: always
MULTIPART_ENABLED: true
MAX_FILE_SIZE: 2MB
MAX_REQUEST_SIZE: 2MB
#-----------------------------------------------------------------------------------------------------------------------
# Spring: JPA:
#-----------------------------------------------------------------------------------------------------------------------
HIBERNATE_DDL_AUTO: create-drop
HIBERNATE_DIALECT: org.hibernate.dialect.H2Dialect
GENERATE_DDL: true
SHOW_SQL: false
OPEN_IN_VIEW: false
DEFAULT_SCHEMA: elethu
H2_CONSOLE_ENABLED: true
#-----------------------------------------------------------------------------------------------------------------------
# Datasource:
#-----------------------------------------------------------------------------------------------------------------------
DATASOURSE_URL: jdbc:h2:mem:ikamva-test;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS elethu
DATASOURSE_USERNAME: ikamva
DATASOURSE_PASSWORD: ikamva
DATASOURSE_DRIVER_CLASS_NAME: org.h2.Driver
#-----------------------------------------------------------------------------------------------------------------------
# Mail:
#-----------------------------------------------------------------------------------------------------------------------
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: TBC
MAIL_PASSWORD: TBC
#-----------------------------------------------------------------------------------------------------------------------
# Logging:
#-----------------------------------------------------------------------------------------------------------------------
LOGGING_FILE_NAME: logs/ikamva-dev-elethu-application.log
LOGGING_ROLLING_POLICY_MAX_HISTORY: 14
LOGGING_ROLLING_POLICY_MAX_FILE_SIZE: 10MB
#----------------------------------------------------------------------------------------------------------------------
# Spring: Profiles:
#-----------------------------------------------------------------------------------------------------------------------
ACTIVE_PROFILE: dev
#-----------------------------------------------------------------------------------------------------------------------
# Spring: Security:
#-----------------------------------------------------------------------------------------------------------------------
JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
JWT_EXPIRATION_IN_MS: 864000000
JWT_REFRESH_EXPIRATION_IN_MS: 604800000
#-----------------------------------------------------------------------------------------------------------------------
#End :: Spring Boot configuration for development environment
#-----------------------------------------------------------------------------------------------------------------------






