server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/ikamvadb
    platform: postgres
    username: zukoyawa
    password: ^Wu3H1bE4Gr*nJxPpTME7!t
    driver-class-name: org.postgresql.Driver
